---
- name: "nos: reset interface to default and then configure it in trunk mode with native-vlan"
  community.network.nos_config:
    lines:
      - "no switchport"
      - "shutdown"
      - "switchport"
      - "switchport mode trunk"
      - "no switchport trunk tag native-vlan"
      - "no shutdown"
      - "no spanning-tree shutdown"
      - "switchport trunk allowed vlan add {{ _vlan_id }}"
      - "switchport trunk native-vlan {{ _vlan_id }}"
    parents:
      - "interface {{ port_name }}"
    match: none
  connection: network_cli

- name: "nos: add the remainder of trunk vlan(s)"
  community.network.nos_config:
    lines:
      - "switchport trunk allowed vlan add {{ t_vlan }}"
    parents:
      - "interface {{ port_name }}"
    match: none
  loop: "{{ trunked_vlans }}"
  loop_control:
    loop_var: t_vlan
  connection: network_cli
