---
- name: "nos: restore config and then configure access port"
  community.network.nos_config:
    lines:
      - "no switchport"
      - "shutdown"
      - "switchport"
      - "switchport mode access"
      - "no shutdown"
      - "no spanning-tree shutdown"
      - "switchport access vlan {{ _vlan_id }}"
    parents:
      - "interface {{ port_name }}"
    match: none
  connection: network_cli
