---
- name: "nos: create vlan"
  community.network.nos_config:
    lines:
      - "name {{ _vlan_name }}"
    parents:
      - "interface vlan {{ _vlan_id }}"
    match: none
  connection: network_cli
